---
- name: Add DNS A Record
  hosts: servers
  gather_facts: no
  tasks:
    - name: Add DNS A record
      win_shell: |
        Add-DnsServerResourceRecord -ZoneName "test.com" -A -Name "demo" -IPv4Address "10.10.70.202"
      become: yes
      become_user: administrator

